runtime: python310  # Or replace '39' with your Python version
entrypoint: gunicorn -b :$PORT nova_test.wsgi  # replace 'myproject'
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: automatic
  max_pending_latency: 10s